---
title: "Elenco pubblicazioni"
author: "`r paste(params$name, params$surname)`"
date: "`r Sys.Date()`"
output: html_document
params:
  name: 
    label: "Name"
    input: text
    value: "Corrado"
  surname:
    label: "Surname"
    input: text
    value: "Lanera"
  data:
    label: "Scopus CSV:"
    value: data-raw/scopus.csv
    input: file
  top_good: 
    label: "Max relevant position from first:" 
    value: 2
    input: slider
    min: 1
    max: 3
    step: 1
  bottom_good: 
    label: "Max relevant position from the last (-1 is the last only, -2 is up to the second to the last, ...):" 
    value: -1
    input: slider
    min: -3
    max: -1
    step: 1
---

<style>
.main-container {
    max-width: 940px;
    margin-left: 0;
    margin-right: auto;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  comment = "",
  message = FALSE,
  warning = FALSE
)

library(here)
library(tidyverse)
library(janitor)
library(DT)
```


## Scopus

```{r, include = FALSE}
scopus <- params$data |> 
  read_csv() |> 
  clean_names() |> 
  rename(
    journal = source_title,
    n_cit = cited_by
  ) |> 
  mutate(
    open = !is.na(open_access),
    authors = str_split(authors, pattern = "\\.; ") |> 
      map(str_to_lower),
    first = map_chr(authors, 1) |>
      map_chr(str_to_title) |> 
      as_factor(),
    last = map_chr(authors, ~.x[[length(.x)]]) |>
      str_to_title() |> 
      as_factor(),
    n_authors = map_int(authors, length),
    my_pos = map_int(authors, str_which, str_to_lower(params[["surname"]])),
    good_pos = (my_pos %in% seq_len(params$top_good)) |
      (n_authors - my_pos < params$bottom_good),
    n_cit = replace_na(n_cit, 0L),
    journal = str_to_title(journal)
  ) |> 
  select(year, journal, title, authors, first, last, my_pos, good_pos, n_authors, n_cit, open, doi)
```


### Journals

```{r, include = FALSE}
journals_n <- scopus |> 
  count(journal) |> 
  arrange(desc(n))
```

```{r, include = FALSE, fig.cap="Source: https://jcr.clarivate.com/jcr/search-results<br>'Good position`: 1, 2, 3, -1, -2"}
# journals_n$journal |> paste(collapse = ",\n") |> cat()
journal_q <- tribble(
  ~ journal,                                                                 ~quartile, ~where, ~impact_factor,
    "International Journal Of Environmental Research And Public Health",       NA,         NA,  NA,
    "Bmc Public Health",                                                       1,         "SCIE",  3.500,
    "International Journal Of Cardiology",                                     2,         "SCIE",  3.200,
    "Journal Of Clinical Medicine",                                            1,         "SCIE",  3.000,
    "Aging Clinical And Experimental Research",                                2,         "SCIE",  3.400,
    "Amia ... Annual Symposium Proceedings. Amia Symposium",                  NA,             NA,    NA,
    "Applied Sciences (Switzerland)",                                          1,         "SCIE",  2.500,
    "Bmc Medical Research Methodology",                                        1,         "SCIE",  3.9,
    "Bmj Open",                                                                1,         "SCIE",  2.4,
    "Critical Care",                                                           1,         "SCIE",  8.8,
    "Diagnostics",                                                             1,         "SCIE",  3.000,
    "Digital Health",                                                          2,         "SCIE",  2.900,
    "Epidemiology Biostatistics And Public Health",                           NA,             NA,    NA,
    "Expert Review Of Medical Devices",                                        3,         "SCIE",  2.900,
    "Health And Social Care In The Community",                                 1,         "SSCI",  2.000,
    "Ijc Heart And Vasculature",                                               2,             NA,  2.500,
    "International Journal Of Food Sciences And Nutrition",                    2,         "SCIE",  3.500,
    "Jacc: Clinical Electrophysiology",                                        1,         "SCIE",  8.000,
    "Jmir Medical Informatics",                                                2,         "SCIE",  3.200,
    "Journal Of Cardiovascular Medicine",                                      2,         "SCIE",  2.900,
    "Journal Of Clinical Epidemiology",                                        1,         "SCIE",  7.300,
    "Journal Of Epidemiology And Community Health",                            1,         "SSCI",  4.900,
    "Journal Of Multidisciplinary Healthcare",                                 2,         "SCIE",  2.700,
    "Journal Of Personalized Medicine",                                        1,         "SCIE",  3.000,
    "Journal Of The American Heart Association",                               1,         "SCIE",  5.000,
    "Journal Of The American Society Of Echocardiography",                     1,         "SCIE",  5.400,
    "Medical Care Research And Review",                                        2,         "SSCI",  2.400,
    "Nutrients",                                                               1,         "SCIE",  4.800,
    "Scientific Reports",                                                      1,         "SCIE",  3.800,
    "Systematic Reviews",                                                      1,         "SCIE",  6.300,
    "The Lancet Planetary Health",                                             1,         "SCIE", 24.200,
    "Children",                                                                2,         "SCIE",  2.000,
    "Bioactive Materials",                                                     1,         "SCIE", 18.000,
    "Neural Regeneration Research",                                            1,         "SCIE",  5.900,
    "Pediatric Research",                                                      1,         "SCIE",  3.100,
    "Mycoses",                                                                 1,         "SCIE",  4.100,
    "Biomolecules",                                                            1,         "SCIE",  4.800,
    "Journal of Pathology",                                                    1,         "SCIE",  5.600,
    "Journal of Thoracic Disease",                                             3,         "SCIE",  2.100,
    "Frontiers in Medicine",                                                   1,         "SCIE",  3.100,
    "Materials Science and Engineering C",                                     2,         "SCIE",  1.842,
    "Frontiers in Oncology",                                                   2,         "SCIE",  3.500,
    "European Journal of Pediatrics",                                          1,         "SCIE",  3.000,
    "European Journal of Cardio-thoracic Surgery",                             1,         "SCIE",  3.300,
    "European Journal of Paediatric Neurology",                                2,         "SCIE",  2.300,
    "Progress in Neurobiology",                                                1,         "SCIE",  6.700,
    "American Journal of Physiology - Lung Cellular and Molecular Physiology", 1,         "SCIE",  3.700,
    "Journal of Clinical Medicine",                                            1,         "SCIE",  3.000,
    "Neurological Sciences",                                                   2,         "SCIE",  2.700,
    "Frontiers In Public Health",                                              2,         "SCIE",  3.000,
    "Interactive Cardiovascular and Thoracic Surgery",                         2,         "SCIE",  1.600,
    "Computational And Mathematical Methods In Medicine",                      2,         "SCIE",  2.809,
    "Healthcare (Switzerland)",                                                2,         "SCIE",  3.160,
    "Plos One",                                                                1,         "SCIE",  2.900,
    "Journal Of Medical Systems",                                              1,         "SCIE",  3.5,
    "Jmir Public Health And Surveillance",                                     1,         "SCIE",  3.5,
    "Epidemiologia E Prevenzione",                                            NA,             NA,   NA
)

journal_q |> 
  arrange(quartile) |> 
  datatable(rownames = FALSE)
```


```{r, fig.cap="Source: https://www.scopus.com/authid/detail.uri?authorId=57194571690"}
scopus_tbl <- scopus |> 
  left_join(journal_q) |>
  relocate(quartile, .after = journal) |>
  arrange(desc(good_pos), quartile)

scopus_tbl |> 
  datatable(filter = "top",
            rownames = FALSE,
            options = list(pageLength = 15, autoWidth = TRUE))
```

Overall IF: `r sum(scopus_tbl[['impact_factor']], na.rm = TRUE)`.

```{r, fig.cap="Source: https://jcr.clarivate.com/jcr/search-results"}
journals_n |> 
  left_join(journal_q) |> 
  relocate(quartile, .after = journal) |>
  arrange(quartile, desc(impact_factor)) |> 
  datatable(rownames = FALSE)
```

